language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

install:
  - (cargo install --force rustfmt-nightly || true)
  - PATH=$PATH:/home/travis/.cargo/bin

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
